version: "3.7"

services:

  mariadb:
    image: "mariadb:10.7.3-focal"
    networks:
      - crawler-network
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: "crawler_dev"
      MARIADB_USER: "crawler"
      MARIADB_PASSWORD: "a-insights"
    volumes:
      - type: bind
        source: ./database/
        target: /docker-entrypoint-initdb.d/

  crawler:
    build: ./crawler
    networks:
      - crawler-network
    depends_on:
      - mariadb
    environment:
      MARIADB_DATABASE: "crawler_dev"
      MARIADB_USER: "crawler"
      MARIADB_PASSWORD: "a-insights"
      MARIADB_HOST: "mariadb"

  loader:
    build: ./data_loader
    networks:
      - crawler-network
    depends_on:
      - mariadb
    environment:
      MARIADB_DATABASE: "crawler_dev"
      MARIADB_USER: "crawler"
      MARIADB_PASSWORD: "a-insights"
      MARIADB_HOST: "mariadb"
    volumes:
    # Mounting local directory to container so that it can read the excel file
      - ./data_loader:/usr/src/app/data_loader  
    command: ["python3", "DataLoader.py"] 

networks:
  crawler-network:
    name: "crawler-network"

